import Head from 'next/head'
import Banner from '../components/banner/banner'
import Navbar from '../components/nav/navbar'
import SectionCard from '../components/sectionCard/sectionCard'
import { getAllVideos, getPopularVideos, getVideos } from '../lib/videos'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney trailers")
  // const disneyVideos = await getAllVideos()
  const productivityVideos = await getVideos("productivity")
  // const productivityVideos = await getAllVideos()
  const travelVideos = await getVideos("travel")
  // const travelVideos = await getAllVideos()
  const popularVideos = await getPopularVideos()
  // const popularVideos = await getAllVideos()

  return {
    props: {disneyVideos, productivityVideos, travelVideos, popularVideos}
  }
}



export default function Home(
  { disneyVideos, travelVideos, productivityVideos, popularVideos }
) {

 

  return (
    <div className={styles.container}>
      <Head>
        <title>NextFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <div className={styles.main}>
        <Navbar username="belegic.dragan@gmail.com" />
        <Banner title="Clifford the red dog" subtitle="a very cute dog"
          imgUrl="/static/images/clifford.jpg"
          videoId="ma67yOdMQfs"
        />
        <div className={styles.sectionWrapper}>
          <SectionCard title="Disney" videos={disneyVideos} size="large" />
          <SectionCard title="Travel" videos={travelVideos} size="small" />
          <SectionCard title="Productivity" videos={productivityVideos} size="medium" />
          <SectionCard title="Popular" videos={popularVideos} size="small" />
        </div>
     </div>
    </div>
  )
}
